### ISSUE TITLE
Grid size 2 dimensions

### ISSUE THREAD

**Issue by sysmaya** [Eldoir/Array2DEditor#1]
Nice component for Unity.
Util for design levels.

Would it be possible to define the size of the grid in two dimensions?
Width and height
By default the grid is square, high equal to wide.

I modify the code slightly to handle Integer data instead  booleans.

Thanks

**Comment by Eldoir** [comment]
Hello,
I just saw you posted this... I'm so sorry for the delay!
I will have a look on this. Thanks! :)

**Comment by Eldoir** [comment]
I've just added that feature 2 years after your request. It's never too late, they say...
Check it out, it also now supports different types! :)

**Comment by HarkoTyrant** [comment]
Hi, thanks for add that feature, but how do you declare the size again?

Let's say i want to declare a Array2DFloat with a size of [2,10] so it shows like that on the inspector.
 Any way to doy it without resizing manually every time on the inspector?
